package:
  name: perses
  version: 0.7.1
source:
  git_url: https://github.com/choderalab/perses.git
  git_tag: 0.7.1
build:
  noarch: python
  preserve_egg_dir: True
  number: 6
  skip: True  # [win or py2k]
  entry_points:
    - perses-relative = perses.app.setup_relative_calculation:run
    - perses-fah = perses.app.fah_generator:run
  script: 
    - ${PYTHON}  -m pip install .  preserve_egg_dir: True
requirements:
  build:
    - python
    - setuptools
    - numpy >=1.14 # [not py36]
    - numpy >=1.14,<1.18 # [py36]
  run:
    - python
    - setuptools
    - ambertools >=19.11
    - numpy >=1.14 # [not py36]
    - numpy >=1.14,<1.18 # [py36]
    - scipy
    - pymbar
    - openmm >=7.4.2
    - parmed
    - openmoltools >=0.8.4
    - openmmtools >=0.20.0
    - numba
    - netcdf4
    - matplotlib
    - seaborn
    - mdtraj
    - pdbfixer
    - lxml
    - networkx >=2.0
    - openeye-toolkits
    - dask
    - distributed
    - yank
    - progressbar2
    - tqdm
    - nose
    - nose-timer
    - dask-jobqueue
    - openmmforcefields
    - openeye-toolkits
    - dicttoxml
test:
  requires:
    - nose
    - nose-timer
  imports:
    - perses
about:
  home: https://github.com/choderalab/perses
  license: MIT
  license_file: LICENSE
  summary: Experiments with expanded ensemble simulation to explore chemical and mutational space
