package:
  name: fragmenter
  version: 0.0.4

source:
  url: https://github.com/openforcefield/fragmenter/archive/0.0.4.tar.gz
  fn: 0.0.4.tar.gz

build:
  preserve_egg_dir: True
  number: 1 # Build number and string do not work together.
  #string: py{{ py }}_a1 # Alpha version 1.
  skip: True # [win or py27 or py35]
  noarch: python
  script: 
    - ${PYTHON}  -m pip install .

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - setuptools
    - openeye-toolkits<2020
    - rdkit
    - pyyaml
    - cmiles
    - networkx

about:
  home: https://github.com/openforcefield/fragmenter
  license: MIT License
  summary: A toolkit to fragment molecules for QM torsion scans and find torsions that need driving.
