
package:
  name: cmiles
  version: 0.1.5

source:
  url: https://github.com/openforcefield/cmiles/archive/v0.1.5.tar.gz
  fn: v0.1.5.tar.gz

build:
  number: 2
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - rdkit

about:
  home: https://github.com/openforcefield/cmiles
  license: MIT
