package:
  name: assaytools
  version: 0.3.0

source:
    git_url: https://github.com/choderalab/assaytools.git
    git_tag: 0.3.0

build:
  number: 1
  #skip: True # [win or py37]
  skip: True # skip for nos

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.14

  run:
    - python
    - numpy >=1.14
    - pint
    - pandas
    - scipy
    - pymc
    - matplotlib
    - seaborn
    - lxml

test:
  requires:
    - nose
    - scripttest
    - pint
    - numpy
    - scipy
    - pymc
    - matplotlib
    - seaborn
    - lxml
  imports:
    - assaytools

about:
  home: https://github.com/choderalab/assaytools
  license: LGPL
  license_file: LICENSE
  summary: A library for the modeling and analysis of plate-based assays (development snapshot)
