package:
  name: openforcefield
  version: 0.7.0

source:
  git_url: https://github.com/openforcefield/openforcefield.git
  git_tag: 0.7.0

build:
  preserve_egg_dir: True
  number: 0 # Build number and string do not work together.
  #string: py{{ py }}_a1 # Alpha version 1.
  skip: True # [win or py27 or py35]

extra:
  #force_upload: True
  upload: main # Upload to anaconda with the "main" label.

requirements:
  build:
    - python
    - setuptools
    # For building sphinx docs
    - sphinx
    - sphinx_bootstrap_theme
    - numpydoc
    - nbsphinx
    - m2r >=0.2.1
    - testpath ==0.3.1
    # Run deps must be installed to build sphinx docs
    - numpy
    - smirnoff99frosst
    - openforcefields
    - openmm
    - networkx
    - rdkit
    - ambertools
    - packaging
    - requests
    - notebook
    # Serialization: Should these be optional?
    - toml
    - bson
    - msgpack-python
    - xmltodict
    - pyyaml
    - cairo >=1.16
  run:
    - python
    - numpy
    - smirnoff99frosst
    - openforcefields
    - openmm
    - networkx
    - rdkit
    - ambertools >=20
    - packaging
    - pytest
    - requests
    - notebook
    # Serialization: Should these be optional?
    - toml
    - bson
    - msgpack-python
    - xmltodict
    - pyyaml
    - cairo >=1.16
    - qcelemental
    - qcportal
    - qcengine # Remove this and py-cpuinfo entry when there's a new release of QCEngine
    - py-cpuinfo ==5 # Needed until https://github.com/MolSSI/QCEngine/issues/252 is resolved+released


about:
  home: https://github.com/openforcefield/openforcefield
  license: MIT
  license_file: LICENSE
  description: The Open Forcefield Toolkit provides implementations of the SMIRNOFF format, parameterization engine, and other tools.
