package:
  name: openmoltools
  version: 0.8.5

source:
  git_url: https://github.com/choderalab/openmoltools.git
  git_tag: v0.8.5

build:
  preserve_egg_dir: True
  number: 0
  skip: True # [win32 or (win and py2k)]

requirements:
  build:
    - python
    - setuptools
    - pandas
    - six
    - mdtraj
    - numpy >=1.14
    - numpydoc
    - scipy
    - pandas
    - openmm >=7.0.1
    - ambertools
    - pytables

  run:
    - python
    - setuptools
    - pandas
    - six
    - mdtraj
    - numpy >=1.14
    - numpydoc
    - scipy
    - openmm >=7.0.1
    - ambertools
    - pytables

#test:
#  imports:
#    - openmoltools
  #commands:
  #  - nosetests openmoltools -v -a '!slow'

about:
  home: https://github.com/choderalab/openmoltools
  license: MIT License
